# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'finished'), (1, 'unfinished')])),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='todo.Task'),
        ),
    ]
