# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20161108_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='todo.Task'),
        ),
    ]
