# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20161109_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='status',
        ),
        migrations.AddField(
            model_name='stage',
            name='achived',
            field=models.BooleanField(default=False),
        ),
    ]
