# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20161110_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='achived',
            new_name='achieved',
        ),
    ]
